/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wckesgfkusqmeylmdokk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indja2VzZ2ZrdXNxbWV5bG1kb2trIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzOTIzMTcsImV4cCI6MjA3NTk2ODMxN30.bknyoTYwn1bxMOx9xNeTDP53v8jBXtjZFFv_GXl--Co"